### ISSUE TITLE
No edges displayed in the graph

### ISSUE THREAD

**Issue by vovak** [VadimFarutin/JB-Test#1]
![image](https://user-images.githubusercontent.com/1163206/95352301-666c8e00-08c2-11eb-9ce1-fa859e7c5835.png)

**Comment by VadimFarutin** [comment]
Only commits created after 2020.01.01 are used to build graph by default (you can change this by passing arguments to main script). Edge abscence shows that there are no common files for a pair of contributors for a selected period (and therefore the weight of this edge is 0).

If you will zoom at the group of points in the center you will see that there are edges between them.

**Comment by VadimFarutin** [comment]
Graph building takes some time, you can comment out that part in main() function and draw graph using data that was saved during previous run.

**Comment by vovak** [comment]
Could you please add a dump of data to the repo?

**Comment by VadimFarutin** [comment]
Added data for a default run.

**Comment by vovak** [comment]
Thank you for swift reaction.
